# Generated by Django 5.1.5 on 2025-02-13 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('posts', '0006_alter_post_author_alter_comment_author_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('device_id', models.CharField(max_length=255, unique=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
