# Generated by Django 5.1.5 on 2025-02-13 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('posts', '0008_alter_customtoken_unique_together_customtoken_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customtoken',
            unique_together={('token', 'device_id')},
        ),
        migrations.AddField(
            model_name='customtoken',
            name='token',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='key',
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='user',
        ),
    ]
