# Generated by Django 5.1.5 on 2025-02-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
