# Generated by Django 5.1.5 on 2025-02-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_customtoken_unique_together_customtoken_token_and_more'),
    ]

    operations = [
    ]
