# Generated by Django 5.1.5 on 2025-02-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_like_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
