# Generated by Django 5.1.5 on 2025-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_like_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-13T00:17:44.502491Z'),
            preserve_default=False,
        ),
    ]
