# Generated by Django 5.1.5 on 2025-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_comment_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='private',
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
